Tegan's edits to The value of Platform Engineering
OctopusSolutionsEngineering/PlatformEngineeringBook pull request #3
Opened 2023-10-23 06:22 UTC by TeganAli

2023-10-24 05:46 UTC, mcasperson approved these changes
lgtm

2023-10-24 05:48 UTC, mcasperson commented on _includes/pe_value.html
> +    throughout your DevOps teams, it is reasonable to argue that your IDP directly:
This needs a closing </p> tag

2023-10-24 05:49 UTC, mcasperson requested changes
The validation check has run and this PR introduces some invalid HTML. This will need to be fixed before we can merge the changes.

2023-10-26 00:34 UTC, TeganAli commented on _includes/pe_value.html
> +    throughout your DevOps teams, it is reasonable to argue that your IDP directly:
```suggestion
    throughout your DevOps teams, it is reasonable to argue that your IDP directly: </p>
```

2023-10-26 00:45 UTC, TeganAli commented on _includes/pe_value.html
> +    throughout your DevOps teams, it is reasonable to argue that your IDP directly:
```suggestion
    throughout your DevOps teams, it is reasonable to argue that your IDP directly:</p>
```

2023-10-26 00:46 UTC, TeganAli commented on _includes/pe_value.html
> +    throughout your DevOps teams, it is reasonable to argue that your IDP directly: </p>
```suggestion
    throughout your DevOps teams, it is reasonable to argue that your IDP directly:</p>
```

2023-10-26 01:33 UTC, TeganAli commented
Hey @mcasperson, I can't work out how to fix the validation issues here, but wondering if I should just copy all my changes over after I create a branch, which might be easier for me, then delete this?

2023-10-26 01:41 UTC, TeganAli commented on _includes/pe_value.html
> +<p>While the ASBX team doesn't specifically describe itself as a platform team, they focus on "undifferentiated work
```suggestion
<p>While the ASBX team doesn't specifically describe itself as a platform team, a focus on "undifferentiated work
```

2023-10-26 01:43 UTC, TeganAli commented on _includes/pe_value.html
> +    <li>Shareholder commitments – have they committed to something to their shareholders, which they'll fail to deliver without your solution?
```suggestion
    <li>Shareholder commitments – have they committed to something to their shareholders, which they'll fail to deliver without your solution?</li>
```

2023-10-26 01:43 UTC, TeganAli commented on _includes/pe_value.html
>      </li>
```suggestion

```

2023-10-29 19:43 UTC, mcasperson approved these changes
The HTML validation check has passed, so this is good to go.

2023-10-29 19:44 UTC, merged